[tool.poetry]
name = "eq-ai"
version = "0.0.1alpha"
description = "[e-ICON] EcoQuest AI API"
authors = ["Juan Lee <me@juany.kr>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
opencv-python = "^4.8.1.78"
mediapipe = "^0.10.7"
requests = "^2.31.0"
pydantic = "^2.5.0"
pydantic-settings = "^2.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
black = "^23.11.0"
isort = "^5.12.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
